export interface Env { DB: D1Database; ASSETS: Fetcher; }
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'content-type':'application/json; charset=utf-8'}});
const bad=(m:string)=>json({error:m},400);
const parse=async<T>(r:Request)=>{try{return await r.json() as T;}catch{return null;}};
const weekStart=()=>{const n=new Date();const day=n.getUTCDay();const diff=(day+6)%7;n.setUTCDate(n.getUTCDate()-diff);n.setUTCHours(0,0,0,0);return n.toISOString().slice(0,10)};
const monthStart=()=>{const n=new Date();return `${n.getUTCFullYear()}-${String(n.getUTCMonth()+1).padStart(2,'0')}-01`;};
export default { async fetch(request:Request, env:Env){const url=new URL(request.url);const path=url.pathname;try{
if(path==='/api/cards'&&request.method==='GET'){const r=await env.DB.prepare(`SELECT id, card_name, bank, last4, card_type, credit_limit, billing_day, due_day, is_active FROM cards ORDER BY is_active DESC, bank, card_name`).all();return json(r.results??[])}
if(path==='/api/transactions'&&request.method==='GET'){const start=url.searchParams.get('start');const end=url.searchParams.get('end');const type=url.searchParams.get('type');const cardId=url.searchParams.get('card_id');const q=url.searchParams.get('q');const c=[] as string[];const p=[] as (string|number)[];if(start){c.push('t.txn_date >= ?');p.push(start)}if(end){c.push('t.txn_date <= ?');p.push(end)}if(type&&['debit','credit'].includes(type)){c.push('t.txn_type = ?');p.push(type)}if(cardId){c.push('t.card_id = ?');p.push(Number(cardId))}if(q){c.push('(LOWER(t.merchant) LIKE ? OR LOWER(COALESCE(t.category,\'\')) LIKE ?)');p.push(`%${q.toLowerCase()}%`,`%${q.toLowerCase()}%`)}const w=c.length?`WHERE ${c.join(' AND ')}`:'';const r=await env.DB.prepare(`SELECT t.id,t.txn_date,t.merchant,t.amount,t.txn_type,t.category,t.notes,c.id as card_id,c.card_name,c.last4,c.bank FROM transactions t LEFT JOIN cards c ON c.id=t.card_id ${w} ORDER BY t.txn_date DESC,t.id DESC LIMIT 1000`).bind(...p).all();return json(r.results??[])}
if(path==='/api/summary'&&request.method==='GET'){const ws=weekStart(), ms=monthStart();const [w,m]=await Promise.all([env.DB.prepare(`SELECT COALESCE(SUM(amount),0) as total FROM transactions WHERE txn_type='debit' AND txn_date >= ?`).bind(ws).first<any>(),env.DB.prepare(`SELECT COALESCE(SUM(amount),0) as total FROM transactions WHERE txn_type='debit' AND txn_date >= ?`).bind(ms).first<any>()]);return json({weeklySpend:w?.total??0,monthlySpend:m?.total??0})}
if(path==='/api/transactions'&&request.method==='POST'){const b=await parse<any>(request);if(!b||!b.txn_date||!b.merchant||!b.amount||!b.txn_type)return bad('txn_date, merchant, amount, txn_type are required');const i=await env.DB.prepare(`INSERT INTO transactions (txn_date, merchant, amount, txn_type, category, notes, card_id) VALUES (?, ?, ?, ?, ?, ?, ?)`).bind(b.txn_date,b.merchant,b.amount,b.txn_type,b.category??null,b.notes??null,b.card_id??null).run();return json({ok:true,id:i.meta.last_row_id},201)}
if(path.startsWith('/api/transactions/')&&request.method==='DELETE'){const id=Number(path.split('/').pop());if(!id)return bad('Invalid transaction id');await env.DB.prepare('DELETE FROM transactions WHERE id=?').bind(id).run();return json({ok:true})}
if(!path.startsWith('/api/')) return env.ASSETS.fetch(request);
return json({error:'Not found'},404)}catch(e){return json({error:e instanceof Error?e.message:'Unknown error'},500)}}};